/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": process.env.VUE_APP_COGNITO_IDENTITY_POOL_ID,
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": process.env.VUE_APP_USER_POOLS_ID,
    "aws_user_pools_web_client_id": process.env.VUE_APP_USER_POOLS_WEB_CLIENT_ID,
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_appsync_graphqlEndpoint": process.env.VUE_APP_APPSYNC_GRAPHQLENDPOINT,
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": process.env.VUE_APP_APPSYNC_APIKEY
};

export default awsmobile;
