name: Auto Testing

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 'v14.17.5'

      - name: Install dependencies
        run: npm ci
      
      - name: Unit Test
        run: npm run test:unit
